name: Helm charts linting
on:
  push:
    branches:
    - main
    paths:
    - 'charts/**'
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: latest

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Run chart-testing (lint)
        run: |
          helm lint charts/*
          helm lint charts/free5gc/charts/*         
        
